name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Build
      run: |
        xcodebuild -project "Touch Bar Simulator.xcodeproj" -scheme "Touch Bar Simulator Reborn" -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO PROVISIONING_PROFILE_SPECIFIER="" -allowProvisioningUpdates

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Touch-Bar-Simulator-Reborn
        path: ~/Library/Developer/Xcode/DerivedData/*/Build/Products/Release/Touch\ Bar\ Simulator\ Reborn.app