name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: |
        xcodebuild -project "Touch Bar Simulator.xcodeproj" -scheme "Touch Bar Simulator" -configuration Release build

    - name: Archive
      run: |
        xcodebuild -project "Touch Bar Simulator.xcodeproj" -scheme "Touch Bar Simulator" -configuration Release -archivePath "Touch Bar Simulator.xcarchive" archive

    - name: Export
      run: |
        xcodebuild -exportArchive -archivePath "Touch Bar Simulator.xcarchive" -exportOptionsPlist export-options.plist -exportPath "export"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Touch-Bar-Simulator
        path: export/